### ISSUE TITLE
(Mac) Application Compile Fail

### ISSUE THREAD

**Issue by fewnew** [LairdCP/UwTerminalX#19]
Hi, I am unable to set up my RM191 Lora development board for sending data to the cloud. I get the error on UwTerminal shown in the image below. Any help is appreciated. Thanks in advance.

<img width="854" alt="screen shot 2018-07-23 at 4 39 57 pm" src="https://user-images.githubusercontent.com/25374395/43109646-a9e9390a-8e9c-11e8-9ab9-9ce580c01a0b.png">

**Comment by thedjnK** [comment]
Hi @fewnew this error is caused because you are attempting to XCompile an application using function definitions from a newer firmware than is loaded on your module. You can download the latest firmware for the RM1xx from the product page: http://www.lairdtech.com/products/rm1xx-lora-modules or alternatively if you wish to stay on the older firmware you will need to reference the documentation and example code for your specific firmware version (which you can get by issuing the 'at i 3' command). Older example code can be found from the releases page on the RM1xx-Applications Github page: https://github.com/LairdCP/RM1xx-Applications/releases

I will mark this issue as resolved.

**Comment by fewnew** [comment]
Hi @thedjnK. Thanks so much for the info. I was able to successfully upgrade my firmware on the devkit but I am unable to move forward because of another issue. Here is a link to the documentation I am following step by step to build a Lora network: https://assets.lairdtech.com/home/brandworld/files/Sentrius%20RG1xx%20Quick%20Start%20Guide%20v2_1.pdf

I am getting the issues below after entering my App EUI, Device EUI, and App Key. Can you kindly please assist me with how I can resolve them?
![error](https://user-images.githubusercontent.com/25374395/43222756-eb2e7e2e-9005-11e8-8299-3511c843a664.png)

Also, is there any other way I could go about this without using The Things Network? Thanks in advance.

**Comment by thedjnK** [comment]
Hi @fewnew word processor systems replace the quote character " with quotes that are slightly left or right orientated such a “ ” - note that these character codes are not the same as the normal quote character. If you look in the automation window at the top 3 lines you can see that the quote characters are not centered. If you replace these characters with normal quote characters and retry the commands then the module will accept them.

Also just to note that UwTerminalX v1.06 is quite old, you can get v1.10a from the [releases page](https://github.com/LairdCP/UwTerminalX/releases)

**Comment by fewnew** [comment]
Thanks @thedjnK. Your replies have been so helpful to me. I really appreciate it. I got the most recent version of UwTerminalX, upgraded the firmware on my gateway too and I was able to change the status to "connected". I also successfully registered my device in the applications page on TTN. When I was trying to run the Lora app I would get the errors shown in the image below. My data tab in TTN shows that I'm not sending any data to the cloud yet. How can I continue please? Thanks.

<img width="918" alt="screen shot 2018-07-27 at 4 41 20 pm" src="https://user-images.githubusercontent.com/25374395/43415946-ced4dbf8-93eb-11e8-9004-93dc746128b2.png">
<img width="1440" alt="screen shot 2018-07-27 at 4 42 39 pm" src="https://user-images.githubusercontent.com/25374395/43415955-d5d7c03c-93eb-11e8-89c7-4df6671c2b84.png">

**Comment by thedjnK** [comment]
Hi @fewnew what application are you using? If you click the 'data' tab from the device view you should see the received data, e.g.:
![image](https://user-images.githubusercontent.com/1551104/43509805-92bc269a-956b-11e8-8c93-161dc69b89aa.png)
