### ISSUE TITLE
'offline' Xcompile

### ISSUE THREAD

**Issue by fchaxel** [LairdCP/UwTerminalX#20]
Hi,

A device, such as BL652, attached to a serial port seems to be mandatory for code compilation.

Any way to compile without it ?

Thank you.

**Comment by thedjnK** [comment]
You can use the XComp_X.exe files included in firmware zips from the Laird Connectivity module websites respectively and XCompile files either by dragging the .sb files onto the XCompiler executable or by running it in a command line view (which will show errors if there are any, e.g. `XComp_BL654_1A64_4F35.exe hw.hello.world.sb`).

Alternatively, you can use the direct web interface on http://uwterminalx.lairdconnect.com/

**Comment by 0ge** [comment]
This is not possible on the other platforms (Mac and Linux) then, I presume?

**Comment by mtwooburn** [comment]
the xcompiler is a purely console mode application.
I have no linux experence, so if you know of an emulation mode in Linux then it should work.

See https://www.winehq.org/

Please let me know if you get this to work.
