### ISSUE TITLE
Dead link to UwFlashX

### ISSUE THREAD

**Issue by 0ge** [LairdCP/UwTerminalX#21]
Navigating to Update tab one can read

> UwFlashX is a new cross-platform firmware upgrade utility for Laird Connectivity modules, information can be found by selecting 'UwFlashX' above."

If one follows the instructions and hit Browse, you get a dead link:
https://github.com/LairdCP/UwFlashX

In fact, I've not heard of UwFlashX and cannot find any information regarding this utility.

**Comment by thedjnK** [comment]
This is an upcoming cross platform utility which will replace UwFlash, it is currently being worked on and will be released in the near future. When it is released, the github project at that link will become active. I will close this issue once it goes live.

**Comment by 0ge** [comment]
Cool! Feel free to close it now, if you wish.

**Comment by thedjnK** [comment]
UwFlashX has been released, closing.
