### ISSUE TITLE
(Windows 10) I can not connect to my dev board

### ISSUE THREAD

**Issue by SongDingQing** [LairdCP/UwTerminalX#26]
I know this could be a silly question, I just got the BL653 dev kit and I try to connect it with UwTerminalX (v1.12a). 
The Guide said that after I plug the board to my PC, and open connection. (pressing ok)
![image](https://user-images.githubusercontent.com/86466959/165448721-efc55d7c-c42d-44d3-88f0-e2a578d943c6.png)
There should be a "00" showing up in the terminal when I hit enter, but Nothing were shown, can someone help me with this.
I tried several ports and none of them shows anything. However, I does receive a message box when I disconnect it.
![image](https://user-images.githubusercontent.com/86466959/165449112-319ca094-f13a-4a32-b8c3-5c71e921e70a.png)
FYI: I downloaded JLink

**Comment by lairdjm** [comment]
That error means that the serial port cannot be opened, perhaps try restarting the PC if this is the first time you've used the device in the PC to allow the drivers to setup properly and ensure you're using the FTDI port (USB1) on the board and that the FTDI is properly installed

**Comment by SongDingQing** [comment]
"ensure you're using the FTDI port (USB1) on the board and that the FTDI is properly installed"
how can I know the FTDI is installed or not

**Comment by lairdjm** [comment]
You can find the drivers on https://ftdichip.com/drivers/
If you go to device manager, start -> devmgmt.msc then under serial ports or USB ports, there should be an FTDI serial port with a COM number if the driver is installed

**Comment by SongDingQing** [comment]
![image](https://user-images.githubusercontent.com/86466959/165900284-03899826-9800-445d-912c-33b8731db39e.png)
I have downloaded the driver and find this configuration under devmgmt.msc
![image](https://user-images.githubusercontent.com/86466959/165900448-a391d7ae-ece3-4696-a1b2-1b7c41dfc2f0.png)
then I used the above configuration and tried to connect the board. However, it is still not showing anything
![image](https://user-images.githubusercontent.com/86466959/165900576-c38a07cd-f430-40a0-8051-0d0e5d0583b0.png)

**Comment by lairdjm** [comment]
Are you sure there is a firmware on the board? You can get the latest firmware on https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bl653-series-bluetooth-51-802154-nfc-module
If you connect up USB2 and run the JLink firmware update batch file, then switch back to USB1 and press enter, you should see a response from the module and be able to develop applications.

**Comment by SongDingQing** [comment]
oh I did not try the firmware, I will try it now!

**Comment by SongDingQing** [comment]
![image](https://user-images.githubusercontent.com/86466959/165902605-8a074677-1840-4256-9993-9d6f9911d64c.png)
I tried using the UwFlashX 1.00 with the above setting, However, it failed

**Comment by lairdjm** [comment]
You won't be able to use UwFlashX if there is no firmware on the board, you must use JLink to initially load the firmware. To do that, run the `Firmware/_DownloadFirmwareJlink.bat` file in the firmware zip with USB2 connected, then once complete switch back to USB1 and check that the module communicates using UwTerminalX, if it does, you can then use UwFlashX to change firmware when needed.

**Comment by SongDingQing** [comment]
![image](https://user-images.githubusercontent.com/86466959/165903746-3404bb53-6d7c-4f51-a3cc-b7246b8e38a0.png)
I saw 00 on the Terminal, but UwFlash does not seem to work

**Comment by lairdjm** [comment]
Serial ports cannot be used by multiple programs at the same time, you must close the serial port if another program is using it prior to using it in another program, you can either click "Close port" in UwTerminalX or exit from the utility, then UwFlashX will be able to open the port.

**Comment by SongDingQing** [comment]
thank you so much, it works now

**Comment by lairdjm** [comment]
Great! :)

**Comment by SongDingQing** [comment]
I tried to upload a program using FTDI USB and it failed
![image](https://user-images.githubusercontent.com/86466959/165908316-725133bf-d3ac-4411-8d5d-18a36c7af908.png)
above is the Message and the instruction I followed is as follow
![image](https://user-images.githubusercontent.com/86466959/165908426-bf7eeb10-f50f-499c-979c-ef05ee90c18d.png)

step 8 is where it went wrong, since it is a official smartBasic file, I am thinking that maybe I did something wrong in configuration.

some more information, I follow the user guide and put all jumper in default position as when I received it,
I did not connect the nfc antenna

**Comment by lairdjm** [comment]
You are using an older firmware version on the board than the latest, the latest firmware version for BL653 is 30.2.3.0, you can either upgrade to this firmware (`BL653/BL653u Firmware for Upgrade v30_2_3_0` on the downloads page) or use an older version of the github applications for older firmware for your firmware version from the releases page: https://github.com/LairdCP/BL653-Applications/releases

**Comment by SongDingQing** [comment]
it works! thank you
