### ISSUE TITLE
(Mac) If the port is disconnected, app crashes

### ISSUE THREAD

**Issue by 0ge** [LairdCP/UwTerminalX#4]
If you open UwTerminalX and connect to a serial port and the port is for some reason disconnected (power failure or unplugged), it crashes.

UwTerminalX v1.02
Mac OSX 10.11.1

**Comment by thedjnK** [comment]
I don't currently have access to a mac. Are you able to download Qt 5.5, compile from source and see if both these issues still occur? If not then I will have a look at them when I'm able to get a mac.

**Comment by 0ge** [comment]
Thanks for replying.
Unfortunately I currently have no possibility to compile from source.

**Comment by 0ge** [comment]
I had some time available and compiled it from source. If I run it in debug, QtCreator will halt at line 64 in UwxPopup.cpp: `ui->text_Message->setPlainText(*strMsg);`. However, if I comment the call to UwxPopup; no dice.

**Comment by thedjnK** [comment]
Appears that Mac enters a continuous loop of disconnected port error which shouldn't happen, will investigate more in future and possibly launch bug report with Qt.

In the mean time I've commented out the problem lines and it no longer crashes, if you have time can you try it and see if it stops the crashing issue for you? https://github.com/LairdCP/UwTerminalX/tree/osx-test

**Comment by thedjnK** [comment]
Submitted bug report to Qt: https://bugreports.qt.io/browse/QTBUG-51210

**Comment by thedjnK** [comment]
This has been fixed in UwTerminalX v1.04, available from https://github.com/LairdCP/UwTerminalX/releases/tag/v1.04

**Comment by 0ge** [comment]
I'm afraid this bug was reintroduced in release 1.05t.

**Comment by thedjnK** [comment]
Is this present in every version since 1.05t or just 1.05t? Are you using a Laird development kit/USB dongle (if so which one) or a module an interfacing it with a non-Laird USB to serial converter (if so which converter chip are you using)? Do you have the Apple drivers for your USB to serial converter or are you using vendor-supplied drivers (e.g. FTDI's drivers from their website)?

**Comment by 0ge** [comment]
I checked all versions from 1.04 and forward. Only 1.04 and 1.05 it worked correctly. 1.05t, 1.06 and 1.08c crashes.
I'm using the DVK-BL600-SA v2. I have also tried with a newer 'stand-alone' module (v7 I believe) with an FTDI chip (FT230XS). I'm using FTDI's driver.

**Comment by thedjnK** [comment]
Fixed in a new build using Qt 5.7.1, available from https://github.com/LairdCP/UwTerminalX/releases/tag/v1.08c_2

**Comment by 0ge** [comment]
Works perfectly, thanks. :)
