### ISSUE TITLE
If corrupted stream, app crashes

### ISSUE THREAD

**Issue by 0ge** [LairdCP/UwTerminalX#5]
If the serial port receives a corrupted stream (e.g. changing baud rate during transfer), the app crashes.

UwTerminalX v1.02
Mac OSX 10.11.1

**Comment by thedjnK** [comment]
Can you provide some additional information or debugging on this (not sure what you mean by changing baud rate during transfer)?
Created simple smartBASIC application that cycles baud rates and outputs data - UwTerminalX on OSX 10.11 hasn't crashed.

**Comment by thedjnK** [comment]
I've tested this but can't reproduce it. Please try in UwTerminalX v1.04 available from https://github.com/LairdCP/UwTerminalX/releases/tag/v1.04 and create a new issue with additional information if the issue is still present.
